### PR TITLE
enhancements 

### PR DESCRIPTION
**Pull request by jumpsmm7**
enhancements for DNSMASQ options, improvements to netprobe option and max client connections, also update for installer version.

### CODE REVIEW

**Comment by jumpsmm7** [comment]
These are enhancements for DNSMASQ, improvements in max client connections, and addition of DNS server for netprobe as well as updating installer version.

Next I would like to help you develop a menu option for specifying relays for Dnscrypt-only servers for new anonymized DNS.

**Comment by thuantran** [comment]
Do you want to adopt this project? Unfortunately I do not have time to maintain it anymore.

**Comment by jumpsmm7** [comment]
sure

**Comment by thuantran** [comment]
I have added you as a collab. Please accept my invitation.

**Comment by jumpsmm7** [comment]
ok I have accepted

**Pull request merged**
